### ISSUE TITLE
Attributes for LdapAuthentification

### ISSUE THREAD

**Issue by ced091** [nitmir/django-cas-server#92] opened 2024-09-11 13:38 UTC
Hello,

I'm come  France.
I had to change the code in the library to retrieve the attributes of an ldap connection.
This is the attibuts_flat method of the Ticket class in the models.py file. You put in the code :
        _**for key, value in self.attributs.items():**_
the self being an instance of the ticket, the attributes dictionary was always empty.
I modified this line to :
        _**for key, value in self.user.attributes.items():**_
(adding the user) and now I can retrieve the user's attributes from the ldap.

Thanks

**Comment by nitmir** [comment] 2024-09-14 16:52
Hello,

I think this is a duplicate of #73 

This is the expected behaviour.

* User.attributes contain all of the user attributes.
* Ticket.attributes contain only the attributes that were selected to be sent to the service then the ticket was created, following the service configuration.

You can see the logic here https://github.com/nitmir/django-cas-server/blob/master/cas_server/models.py#L400 in the User class.

```python
        service_attributs = {}
        for (key, value) in self.attributs.items():
            if key in attributs or '*' in attributs:
                if key in replacements:
                    if isinstance(value, list):
                        for index, subval in enumerate(value):
                            value[index] = re.sub(
                                replacements[key][0],
                                replacements[key][1],
                                subval
                            )
                    else:
                        value = re.sub(replacements[key][0], replacements[key][1], value)
                service_attributs[attributs.get(key, key)] = value
        ticket = ticket_class.objects.create(
            user=self,
            attributs=service_attributs,
            service=service,
            renew=renew,
            service_pattern=service_pattern,
            single_log_out=service_pattern.single_log_out
        )
        ticket.save()

```

This also allows to rename some attribute name or to transform the attribute value for a specific service.

By default, no attributes are sent to a service (except the username). This is the default for privacy reasons.  As you can see it in the doc there https://github.com/nitmir/django-cas-server#service-patterns, you have to define the list of attributes to send for each service:
> `Replace attribute names`: a list of user attributes to send to the service.

You can use `*` as an attribute name in the list to send all attributes.

If you have any suggestion to improve the README to make it more obvious, please open a merge request.

When the list of attribute is defined for a service, attributes get sent.

So I'll close this issue request.

Cheers

**Closed by nitmir** 2024-09-14 16:52 UTC
